language: node_js
node_js:
  - "lts/*"

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "hNMUO7hjisZINuLLanTsq947Su9gujFtswyELPMHWcTJ0XaIbopA7hdh1szqYA7eHns472lU5kq3AplYtxtAZY2oFCW3FgFje7u4t2hSzacwP+BE0erIyOLz0iDoYAxA7ZUq55Kqa5ckvGaj5R8EwJnuzXuMunqko277sWu3b/1u8kvMWbZ8S1dVd2MpKBqjvWJPfhT+fC5swtJ+VA3hON1FWcNQhGGEHzd3mawgdBcbZurtgAVE9+Uy5S7J/2PyaXxCKZkmJAsfmFi8cS1FPSjdQbPhRS0iQDTsPiZ2/1sxkMN44GV42ZwCXYQYSsrfqI6TP317EAVcimUHTEZXCp37DPFZJKvgGnD+xMWS2uSk2TPao72BF0wCww7+otQmoKJ0qzDUNmJ+IxZI7+8kzqmFdGsJq2TUWiAsyzRKBeZYqLmAyUNOiAFjFZdTmtaMvv/+mzMalfA7IgAkuHxtt/q0dbSRpmeacmeDe77nbBt/F+KyB7R8La6tQSte4zZ3xud12bgk/Zt/smSuOeUvK7/UFd4kx5HaIom6hWtHqN3zJ0euYixsxM9GugpCF4wKEM6DLAViw3cVWRv+lKpDyIziidis+CRZSfQhSmBhwGimTjjxO5HyOHVeCDtLCbn08RtojvxHcVZsPk/OG5ij0tkd3Ot9PGg6tOPEyN+oCS4="
env:
  secure: "Uyr3CCX/MAYx07zw8jYPNL97oMPxdiUQcY5PZeL76ocqd64mhnxQV0VhQ0MtS98tsKXWWYFrc4nuE77SOuFxszq3cM2ZwzlZ4eYnMUB9scEQpVudBb2cdDU3a66DWOAplLUqszujIAAqPgJY9Vu1UND02VOqJKNCNpOnDBwDRkWcViEQoUBnHXHepyRSch8ajLS6DplMZ88stTV0oD0ovpawqu3a/nz+qyDR8cON1r+gp9o+/CX7usH484joV9K6dZG6VOWx4utlnWD56fbirlk0fKbMq9Erf9+aobm3OS+x0N9QZONFf7keOVmWkV8PkUvqNmbFSv2Jok5ifM9IusOEKD/3ma8vxB06jZScvdEN3Ws1euPi1aM5O/pUPEE8zN7FxypAJf4ZpAYkbS+zVoPceHkMqatfozA6LuEKLkb3hhn5QTl01+3hWQACp8cwRmuoR0XHxhUvNk8ASTecqELsyWdXt5SaEMT4Bbc1NdN27i7joUl3Nxkjkwk3zaLSwGNlI7a/DvZ40TfJ8fOOgPPeT2tTWwK8NWrLznVM6ecgI1rhOSfsKGlqHniTc5/IS2f1wCSOX9EutIj6z0esyZCiLgxzBE5qwkmOMJ3ILJjqIUTkqanxkYbLawkr/vEHBu3NupU1My/aZasoNgEMCi34alzb+eo2eNYFxPV3tM4="

cache:
  directories:
    - "node_modules"

install:
  - "npm install"
  - "npm install -g snyk"

script:
  - "npm run test"
  - "npm run build"
  - "sonar-scanner"

after_success:
  - snyk monitor
